import type { Metadata } from "next";
import "./globals.css";
import { ThemeToggle } from "@/components/common/theme-toggle";
import Providers from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
        <Providers>
          <div className="flex flex-col h-full w-screen">
            <div className="p-4">
              <ThemeToggle />
            </div>
            <div className="flex-1 overflow-auto">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
